Student: Pozdnikin Mykhailo
Group: CE-47
Subject: CSDT

Project name: PongGame
Programming language: C

Additional tools/utils: Bash, Make
HW interface: UART
Data driven format: xml

Play modes: Man vs AI, Man vs Man, AI vs AI

AI supports next complexity levels: Random move, Win strategy

Actions: New, Save, Load

The proposal for data driven approach: configuration (saved in configuration file or DB): board size, distance, tool size, win statement, lose statement, AI parameters
